ALTER TABLE "liquidaciones" ADD COLUMN IF NOT EXISTS "materialPrincipal" TEXT;
ALTER TABLE "liquidaciones" ADD COLUMN IF NOT EXISTS "muestraFisica" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "liquidaciones" ADD COLUMN IF NOT EXISTS "retazosConfeccion" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "liquidaciones" ADD COLUMN IF NOT EXISTS "retazosConfeccionMetros" DOUBLE PRECISION;
ALTER TABLE "liquidaciones" ADD COLUMN IF NOT EXISTS "plantillas" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "liquidaciones" ADD COLUMN IF NOT EXISTS "estampadoPiezas" INTEGER;
ALTER TABLE "liquidaciones" ADD COLUMN IF NOT EXISTS "bordadoPiezas" INTEGER;
ALTER TABLE "liquidaciones" ADD COLUMN IF NOT EXISTS "fusionadosPiezas" INTEGER;
ALTER TABLE "liquidaciones" ADD COLUMN IF NOT EXISTS "registroTiqueteadas" JSONB NOT NULL DEFAULT '{}';
ALTER TABLE "liquidaciones" ADD COLUMN IF NOT EXISTS "despachoPaquetes" INTEGER;
ALTER TABLE "liquidaciones" ADD COLUMN IF NOT EXISTS "despachoRollos" INTEGER;
